# This flake was initially generated by fh, the CLI for FlakeHub (version 0.1.10)
{
  
  description = "Uhaul SH";

  
  inputs = {
    flake-schemas.url = "https://flakehub.com/f/DeterminateSystems/flake-schemas/*.tar.gz";

    nixpkgs.url = "https://flakehub.com/f/NixOS/nixpkgs/*.tar.gz";
  };

  
  outputs = { self, flake-schemas, nixpkgs }:
    let
      
      supportedSystems = [ "x86_64-linux" "aarch64-darwin" "x86_64-darwin" "aarch64-linux" ];
      forEachSupportedSystem = f: nixpkgs.lib.genAttrs supportedSystems (system: f {
        pkgs = import nixpkgs { inherit system; };
      });
    in {
      formatter = forEachSupportedSystem ({pkgs}: pkgs.nixfmt-rfc-style);

      schemas = flake-schemas.schemas;

      
      devShells = forEachSupportedSystem ({ pkgs }: {
        default = pkgs.buildFHSUserEnv {
          name = "devfs";
          runScript = "bash";
          targetPkgs = pkgs: with pkgs; [
            bash
            patchelf
            coreutils
          ]; 
        };
      });
    };
}
